# Generated by Django 5.0.6 on 2024-06-26 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalprojectassignment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalprojectphase',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='projectassignment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ManyToManyField(blank=True, related_name='project_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='updated_by',
            field=models.ManyToManyField(blank=True, related_name='assignment_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='updated_by',
            field=models.ManyToManyField(blank=True, related_name='projectphase_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
