# Generated by Django 4.2.4 on 2024-01-25 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_projectassignment_historicalprojectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_by',
            field=models.ManyToManyField(blank=True, related_name='project_assigned_by', through='projects.ProjectAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='project_assigned_to', through='projects.ProjectAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
