# Generated by Django 5.0.6 on 2024-07-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_historicalproject_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojectphase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='status',
        ),
    ]
