# Generated by Django 5.0.6 on 2024-06-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0002_alter_historicalphase_status_alter_phase_status'),
        ('projects', '0003_alter_historicalproject_status_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='phases',
            field=models.ManyToManyField(blank=True, through='projects.ProjectPhase', to='phases.phase'),
        ),
    ]
