# Generated by Django 5.0.6 on 2024-06-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_historicalproject_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
