# Generated by Django 4.2.4 on 2023-10-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsegment',
            name='phases',
        ),
        migrations.RemoveField(
            model_name='historicalsegment',
            name='stages',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='phases',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='stages',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='tags',
        ),
    ]
