# Generated by Django 5.0.6 on 2024-06-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsegment',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('0', 'Close')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='segment',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('0', 'Close')], default='1', max_length=2),
        ),
    ]
