# Generated by Django 5.0.6 on 2024-06-26 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0002_remove_historicalsegment_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsegmentassignment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='segmentassignment',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='segmentassignment',
            name='updated_by',
            field=models.ManyToManyField(blank=True, related_name='segment_assignment_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
