# Generated by Django 4.2.4 on 2024-01-25 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('segments', '0002_segmentassignment_historicalsegmentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='assigned_by',
            field=models.ManyToManyField(blank=True, related_name='segment_assigned_by', through='segments.SegmentAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='segment',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='segment_assigned_to', through='segments.SegmentAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
