# Generated by Django 5.0.6 on 2024-06-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0002_alter_historicalsegment_status_alter_segment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsegmentassignment',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='segmentassignment',
            name='assigned_at',
        ),
    ]
