# Generated by Django 5.0.6 on 2024-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_sprintphase_created_at_sprintphase_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsprintphase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalsprintproject',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalsprintsegment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalsprintticket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sprintphase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sprintproject',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sprintsegment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sprintticket',
            name='status',
        ),
        migrations.AlterField(
            model_name='historicalsprint',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('0', 'Close')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('0', 'Close')], default='1', max_length=2),
        ),
    ]
