# Generated by Django 4.2.4 on 2024-02-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercompanydetails',
            name='company_sub_domain_name',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomercompanydetails',
            name='company_sub_domain_name',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
