# Generated by Django 5.0.6 on 2024-06-26 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcompany',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalcustomercompanydetails',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customercompanydetails',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ManyToManyField(blank=True, related_name='company_model_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercompanydetails',
            name='updated_by',
            field=models.ManyToManyField(blank=True, related_name='company_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
