# Generated by Django 4.2.4 on 2023-09-11 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_gender_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved_to_be_in_touch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
