# Generated by Django 4.2.4 on 2023-10-12 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('segments', '0002_remove_historicalsegment_phases_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_remove_historicalproject_phases_and_more'),
        ('sprints', '0001_initial'),
        ('stages', '0001_initial'),
        ('milestones', '0001_initial'),
        ('tickets', '0002_post_alter_historicalticket_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='sprints',
            field=models.ManyToManyField(blank=True, to='sprints.sprint'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='stages',
            field=models.ManyToManyField(blank=True, to='stages.stage'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmilestone',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.customercompanydetails'),
        ),
        migrations.AddField(
            model_name='historicalmilestone',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmilestone',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmilestone',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project'),
        ),
        migrations.AddField(
            model_name='historicalmilestone',
            name='segment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='segments.segment'),
        ),
        migrations.AddField(
            model_name='historicalmilestone',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
