# Generated by Django 5.0.6 on 2024-06-26 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmilestone',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='milestone',
            name='updated_by',
            field=models.ManyToManyField(blank=True, related_name='milestone_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
