# Generated by Django 5.0.6 on 2024-07-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmilestone',
            name='completion_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='completion_date',
            field=models.DateTimeField(),
        ),
    ]
