# Generated by Django 4.2.4 on 2024-01-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphase',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalphase',
            name='status',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalphase',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='phase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
