# Generated by Django 5.0.6 on 2024-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphase',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('0', 'Close')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('0', 'Close')], default='1', max_length=1),
        ),
    ]
