# Generated by Django 5.0.6 on 2024-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_remove_invitation_updated_by_invitation_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('0', 'Close')], default='1', max_length=2),
        ),
    ]
