# Generated by Django 4.2.4 on 2023-09-29 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stages', '0001_initial'),
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Active tickets represent tickets or issues that are currently being worked on, are in progress, or are actively being addressed by team members.'), ('2', 'Inactive tickets represent tickets or issues that are not currently being worked on, have been completed, or have been put on hold for various reasons like, a ticket has been postponed, deprioritized, or is awaiting further action.'), ('3', 'When candidate finishes the task, he can move the ticket to a Finished stage. Completed tickets are the one which was marked as Completed by Any Assigner.'), ('4', 'When this task or ticket is suddenly not required future or not important or need to do later based on another requirement, On Hold tickets are the one which was marked as On Hold by Any Assigner.')], default='1', max_length=1)),
                ('priority_type', models.CharField(choices=[('1', 'Text Option allows to select priority using High, Medium and Low for a ticket.'), ('2', 'Scale Option allows to select priority using 1 to 10 for a ticket.')], default='1', max_length=1)),
                ('priority', models.CharField(choices=[('1', "This level is used for tasks or issues that require immediate attention or have a significant impact on the project, business, or customer satisfaction. High-priority items are typically those that need to be resolved or addressed as soon as possible. It's 'good' to use this level for critical issues that genuinely require urgent action."), ('2', "Medium-priority items are important but not as urgent as high-priority tasks. They might have a significant impact if not addressed promptly but don't require immediate attention. These are often used for tasks or issues that need to be addressed in the near future but can wait for a short period. It's 'good' to use this level for important tasks that need to be scheduled and managed carefully."), ('3', "Low-priority items are not time-sensitive and can be addressed at a later date without significant negative consequences. These are often used for tasks or issues that are nice-to-have but not critical for the current phase of a project or operation. It's 'good' to use this level for non-urgent, lower-impact items that can be deprioritized when higher-priority tasks emerge.")], default='2', max_length=1)),
                ('priority_scale', models.CharField(choices=[('10', 'High'), ('09', 'High'), ('08', 'High'), ('07', 'High'), ('06', 'MEDIUM'), ('05', 'MEDIUM'), ('04', 'MEDIUM'), ('03', 'LOW'), ('02', 'LOW'), ('01', 'LOW')], default='01', max_length=2)),
                ('ticket_type', models.CharField(choices=[('01', 'A Bug is a flaw or error in a computer program that causes it to behave in an unintended or unexpected way. A bug has to be resolved.'), ('02', 'A Feature is a new block that has to be implemented based on a idea.'), ('03', 'If you want to add more or update something, Enhancement is the one to choose.'), ('04', "If you're using Agile methodologies like Scrum, you might use this to describe user requirements. User stories focus on delivering value to the end-user."), ('05', 'This category can be used to track tasks related to code refactoring, code quality improvements, and addressing technical issues that may not be visible to end-users but need attention. Make sure to add all the necessary sub tickets and super tickets.'), ('06', 'Tasks related to creating or updating documentation, including user manuals, API documentation, or internal documentation.'), ('07', 'For tasks that involve investigating new technologies, evaluating potential solutions, or conducting market research.'), ('08', 'Tasks related to deploying code to production, configuring servers, or managing deployment pipelines.'), ('09', 'Tasks related to quality assurance and testing efforts, including test case creation, test execution, and bug verification.'), ('10', 'If your project involves ongoing support for end-users, you can use this category to track support requests and issues.'), ('11', 'Tasks related to identifying and addressing security vulnerabilities or implementing security features.'), ('12', 'For tasks related to server maintenance, cloud infrastructure management, or network configuration.'), ('13', 'If your project must adhere to specific regulations or compliance standards, you can use this category to track tasks related to compliance efforts.'), ('14', 'Tasks related to data management, data migration, or database schema changes.'), ('15', 'Tasks focused on optimizing system performance, including profiling, benchmarking, and optimization efforts.'), ('16', 'Tasks related to improving the overall user experience, including user interface design and usability testing.'), ('17', 'If your project is available in multiple languages, you can use this category for tasks related to translation and localization.'), ('18', 'Tasks related to training team members or end-users on how to use the software or tools effectively.')], default='02', max_length=2)),
                ('deleted', models.CharField(choices=[('1', 'This ticket was deleted by user.'), ('2', 'This tickect was not deleted by user.')], default='1', max_length=1)),
                ('company_ticket_counter', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ManyToManyField(blank=True, related_name='ticket_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='ticket_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_created_by', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='ticket_members', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_segment', to='segments.segment')),
                ('stages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_stages', to='stages.stage')),
                ('sub_tickets', models.ManyToManyField(blank=True, related_name='tickets_sub_tickets', to='tickets.ticket')),
                ('super_tickets', models.ManyToManyField(blank=True, related_name='tickets_super_tickets', to='tickets.ticket')),
                ('tags', models.ManyToManyField(blank=True, related_name='ticket_tags', to='tags.tag')),
                ('updated_by', models.ManyToManyField(blank=True, related_name='ticket_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('estimated_end_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Active tickets represent tickets or issues that are currently being worked on, are in progress, or are actively being addressed by team members.'), ('2', 'Inactive tickets represent tickets or issues that are not currently being worked on, have been completed, or have been put on hold for various reasons like, a ticket has been postponed, deprioritized, or is awaiting further action.'), ('3', 'When candidate finishes the task, he can move the ticket to a Finished stage. Completed tickets are the one which was marked as Completed by Any Assigner.'), ('4', 'When this task or ticket is suddenly not required future or not important or need to do later based on another requirement, On Hold tickets are the one which was marked as On Hold by Any Assigner.')], default='1', max_length=1)),
                ('priority_type', models.CharField(choices=[('1', 'Text Option allows to select priority using High, Medium and Low for a ticket.'), ('2', 'Scale Option allows to select priority using 1 to 10 for a ticket.')], default='1', max_length=1)),
                ('priority', models.CharField(choices=[('1', "This level is used for tasks or issues that require immediate attention or have a significant impact on the project, business, or customer satisfaction. High-priority items are typically those that need to be resolved or addressed as soon as possible. It's 'good' to use this level for critical issues that genuinely require urgent action."), ('2', "Medium-priority items are important but not as urgent as high-priority tasks. They might have a significant impact if not addressed promptly but don't require immediate attention. These are often used for tasks or issues that need to be addressed in the near future but can wait for a short period. It's 'good' to use this level for important tasks that need to be scheduled and managed carefully."), ('3', "Low-priority items are not time-sensitive and can be addressed at a later date without significant negative consequences. These are often used for tasks or issues that are nice-to-have but not critical for the current phase of a project or operation. It's 'good' to use this level for non-urgent, lower-impact items that can be deprioritized when higher-priority tasks emerge.")], default='2', max_length=1)),
                ('priority_scale', models.CharField(choices=[('10', 'High'), ('09', 'High'), ('08', 'High'), ('07', 'High'), ('06', 'MEDIUM'), ('05', 'MEDIUM'), ('04', 'MEDIUM'), ('03', 'LOW'), ('02', 'LOW'), ('01', 'LOW')], default='01', max_length=2)),
                ('ticket_type', models.CharField(choices=[('01', 'A Bug is a flaw or error in a computer program that causes it to behave in an unintended or unexpected way. A bug has to be resolved.'), ('02', 'A Feature is a new block that has to be implemented based on a idea.'), ('03', 'If you want to add more or update something, Enhancement is the one to choose.'), ('04', "If you're using Agile methodologies like Scrum, you might use this to describe user requirements. User stories focus on delivering value to the end-user."), ('05', 'This category can be used to track tasks related to code refactoring, code quality improvements, and addressing technical issues that may not be visible to end-users but need attention. Make sure to add all the necessary sub tickets and super tickets.'), ('06', 'Tasks related to creating or updating documentation, including user manuals, API documentation, or internal documentation.'), ('07', 'For tasks that involve investigating new technologies, evaluating potential solutions, or conducting market research.'), ('08', 'Tasks related to deploying code to production, configuring servers, or managing deployment pipelines.'), ('09', 'Tasks related to quality assurance and testing efforts, including test case creation, test execution, and bug verification.'), ('10', 'If your project involves ongoing support for end-users, you can use this category to track support requests and issues.'), ('11', 'Tasks related to identifying and addressing security vulnerabilities or implementing security features.'), ('12', 'For tasks related to server maintenance, cloud infrastructure management, or network configuration.'), ('13', 'If your project must adhere to specific regulations or compliance standards, you can use this category to track tasks related to compliance efforts.'), ('14', 'Tasks related to data management, data migration, or database schema changes.'), ('15', 'Tasks focused on optimizing system performance, including profiling, benchmarking, and optimization efforts.'), ('16', 'Tasks related to improving the overall user experience, including user interface design and usability testing.'), ('17', 'If your project is available in multiple languages, you can use this category for tasks related to translation and localization.'), ('18', 'Tasks related to training team members or end-users on how to use the software or tools effectively.')], default='02', max_length=2)),
                ('deleted', models.CharField(choices=[('1', 'This ticket was deleted by user.'), ('2', 'This tickect was not deleted by user.')], default='1', max_length=1)),
                ('company_ticket_counter', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='segments.segment')),
                ('stages', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stages.stage')),
            ],
            options={
                'verbose_name': 'historical ticket',
                'verbose_name_plural': 'historical tickets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
