# Generated by Django 5.0.6 on 2024-06-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinnedpost',
            name='pinned_by',
        ),
        migrations.RemoveField(
            model_name='pinnedpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='parent_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='saved_by',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voted_by',
        ),
        migrations.DeleteModel(
            name='HistoricalPost',
        ),
        migrations.DeleteModel(
            name='PinnedPost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='SavedPost',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
