# Generated by Django 4.2.4 on 2024-01-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
    ]
