# Generated by Django 4.2.4 on 2023-10-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
        ('tickets', '0002_post_alter_historicalticket_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='stages',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='stages',
        ),
        migrations.CreateModel(
            name='TicketStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stage')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='stages',
            field=models.ManyToManyField(through='tickets.TicketStage', to='stages.stage'),
        ),
    ]
