# Generated by Django 5.0.6 on 2024-07-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_historicalticketassignment_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticketstage',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketstage',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
