# Generated by Django 4.2.4 on 2024-01-28 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_ticketassignment_historicalticketassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_by',
            field=models.ManyToManyField(blank=True, related_name='ticket_assigned_by', through='tickets.TicketAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='ticket_assigned_to', through='tickets.TicketAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
