# Generated by Django 4.2.4 on 2024-01-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_assigned_by_ticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpost',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
