# Generated by Django 4.2.4 on 2024-01-31 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_historicalpost_downvotes_historicalpost_upvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedpost',
            name='saved',
            field=models.CharField(choices=[('1', 'This post was saved by user.'), ('2', 'This post was not saved by user.')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='PinnedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.CharField(choices=[('1', 'This post was pinned by user.'), ('2', 'This post was not pinned by user.')], default='1', max_length=1)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_pinned_by', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_posts', to='tickets.post')),
            ],
        ),
    ]
