# Generated by Django 4.2.4 on 2024-01-31 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_savedpost_saved_pinnedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='accepted_solution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='parent_post',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tickets.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='accepted_solution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tickets.post'),
        ),
    ]
